# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(804, 537)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/wang/Desktop/jn.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.selectPicPushButton = QtWidgets.QPushButton(Dialog)
        self.selectPicPushButton.setGeometry(QtCore.QRect(170, 460, 211, 61))
        self.selectPicPushButton.setAutoDefault(False)
        self.selectPicPushButton.setObjectName("selectPicPushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 10, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(590, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        self.scrollBar = QtWidgets.QScrollBar(Dialog)
        self.scrollBar.setGeometry(QtCore.QRect(20, 419, 761, 31))
        self.scrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar.setObjectName("scrollBar")
        self.originPic = QtWidgets.QLabel(Dialog)
        self.originPic.setGeometry(QtCore.QRect(40, 40, 311, 321))
        self.originPic.setObjectName("originPic")
        self.predPic = QtWidgets.QLabel(Dialog)
        self.predPic.setGeometry(QtCore.QRect(450, 40, 311, 321))
        self.predPic.setObjectName("predPic")
        self.predPicPushButton = QtWidgets.QPushButton(Dialog)
        self.predPicPushButton.setGeometry(QtCore.QRect(440, 460, 211, 61))
        self.predPicPushButton.setAutoDefault(False)
        self.predPicPushButton.setObjectName("predPicPushButton")
        self.label_num = QtWidgets.QLabel(Dialog)
        self.label_num.setGeometry(QtCore.QRect(390, 380, 72, 15))
        self.label_num.setObjectName("label_num")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "息肉检测系统"))
        self.selectPicPushButton.setText(_translate("Dialog", "选择图片"))
        self.label.setText(_translate("Dialog", "原始图像"))
        self.label_2.setText(_translate("Dialog", "预测图像"))
        self.originPic.setText(_translate("Dialog", "originPic"))
        self.predPic.setText(_translate("Dialog", "predPic"))
        self.predPicPushButton.setText(_translate("Dialog", "开始检测"))
        self.label_num.setText(_translate("Dialog", "num"))
